.TH Tester 1 "April 23 2018"

.SH NAME
tester \(em a lightweight, cross-platform program to test competitive programming problems locally.

.SH SYNOPSIS
.B tester

.SH DESCRIPTION

.SH What is Tester?
\fBTester\fR is an application that can test competitive programming problems. It is very easy to use. No Internet connection required to test the problems \(em you'll just need the tests. It can import archives like Polygon's. You can also create a problem in it \(em Tester has its own problem properties editor.

.SH Why use Tester?
.IP "   \(bu" 6
It's a native, lightweight application.
.IP "   \(bu" 6
It doesn't require much space and can be distributed in a single executable.
.IP "   \(bu" 6
It's cross-platform and available on Windows and GNU/Linux
.IP "   \(bu" 6
No more batch scripts like All_Test.bat! Tester provides an intuitive graphical interface.
.IP "   \(bu" 6
It can automatially import problems.
.IP "   \(bu" 6
Tester uses JSON to save problems' properties, so they can be easily parsed.
.IP "   \(bu" 6
Testing results can be saved to JSON and can be easily parsed, too.

.SH SEE ALSO
\fBtsrun\fP(1)

.SH AUTHORS
Alexander Kernozhitsky <sh200105@mail.ru>
