Document: tester
Title: Debian tester Manual
Author: <insert document author here>
Abstract: This manual describes what tester is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tester/tester.sgml.gz

Format: postscript
Files: /usr/share/doc/tester/tester.ps.gz

Format: text
Files: /usr/share/doc/tester/tester.text.gz

Format: HTML
Index: /usr/share/doc/tester/html/index.html
Files: /usr/share/doc/tester/html/*.html
