{
  This file is part of Tester

  Copyright (C) 2017 Alexander Kernozhitsky <sh200105@mail.ru>

  This program is free software; you can redistribute it and/or modify it under
  the terms of the GNU General Public License as published by the Free
  Software Foundation; either version 2 of the License, or (at your option)
  any later version.

  This code is distributed in the hope that it will be useful, but WITHOUT ANY
  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
  FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
  details.

  A copy of the GNU General Public License is available on the World Wide Web
  at <http://www.gnu.org/copyleft/gpl.html>. You can also obtain it by writing
  to the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston,
  MA 02111-1307, USA.
}

'.scoreTable {'                           + LineEnding +
IndentFill + 'border-collapse: collapse;' + LineEnding +
IndentFill + 'border: thin solid black;'  + LineEnding +
IndentFill + 'font-family: sans-serif;'   + LineEnding +
'}'                                       + LineEnding +
'.tableCell {'                            + LineEnding +
IndentFill + 'border: thin solid black;'  + LineEnding +
IndentFill + 'text-align: center;'        + LineEnding +
IndentFill + 'vertical-align: middle;'    + LineEnding +
IndentFill + 'padding: 4px;'              + LineEnding +
IndentFill + 'white-space: nowrap;'       + LineEnding +
'}'                                       + LineEnding +
'.headerCell {'                           + LineEnding +
IndentFill + 'background-color: silver;'  + LineEnding +
'}'                                       + LineEnding +
'.bigDataText {'                          + LineEnding +
IndentFill + 'font-size: 150%;'           + LineEnding +
IndentFill + 'font-weight: bold;'         + LineEnding +
'}'                                       + LineEnding +
'.smallDataText {'                        + LineEnding +
IndentFill + ' font-size: 75%;'           + LineEnding +
'}'

