{
  This file is part of Tester

  Copyright (C) 2017 Kernozhitsky Alexander <sh200105@mail.ru>

  This program is free software; you can redistribute it and/or modify it under
  the terms of the GNU General Public License as published by the Free
  Software Foundation; either version 2 of the License, or (at your option)
  any later version.

  This code is distributed in the hope that it will be useful, but WITHOUT ANY
  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
  FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
  details.

  A copy of the GNU General Public License is available on the World Wide Web
  at <http://www.gnu.org/copyleft/gpl.html>. You can also obtain it by writing
  to the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston,
  MA 02111-1307, USA.
}

'.scoreTable {'                  + LineEnding +
'    border-collapse: collapse;' + LineEnding +
'    border: thin solid black;'  + LineEnding +
'    font-family: sans-serif;'   + LineEnding +
'}'                              + LineEnding +
'.tableCell {'                   + LineEnding +
'    border: thin solid black;'  + LineEnding +
'    text-align: center;'        + LineEnding +
'    vertical-align: middle;'    + LineEnding +
'    padding: 4px;'              + LineEnding +
'    white-space: nowrap;'       + LineEnding +
'}'                              + LineEnding +
'.headerCell {'                  + LineEnding +
'    background-color: silver;'  + LineEnding +
'}'                              + LineEnding +
'.bigDataText {'                 + LineEnding +
'    font-size: 150%;'           + LineEnding +
'    font-weight: bold;'         + LineEnding +
'}'                              + LineEnding +
'.smallDataText {'               + LineEnding +
'    font-size: 75%;'            + LineEnding +
'}'

